
#   spring.datasource.url: jdbc:mysql://localhost:3306/blogengine
#   spring.datasource.username: root
#   spring.datasource.password: testtest
#   driver: com.mysql.jdbc.Driver
#   spring.liquibase.enabled: true
#   spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blogengine}
spring.datasource.username: root
spring.datasource.password: testtest
driver: com.mysql.jdbc.Driver
spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
server.port: ${PORT:8080}

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB


# init
blog.title: "DevPub"
blog.subtitle: "Рассказы разработчиков"
blog.phone: "+7 903 666-44-55"
blog.email: "mail@mail.ru"
blog.copyright: "Дмитрий Сергеев"
blog.copyrightFrom: "2005"

captcha.delete: 1 #hour

